version: '3.8'

services:
  # NGINX Reverse Proxy - Only ports 80/443 exposed
  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    ports:
      - "80:80"   # HTTP (redirect to HTTPS)
      - "443:443" # HTTPS only
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - api-gateway
    networks:
      - backend-network
      - frontend-network
    restart: unless-stopped

  # API Gateway - Internal only, no external ports
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    # NO external ports - only accessible via nginx
    expose:
      - "8000"
    env_file:
      - ./api-gateway/.env
    environment:
      - NEED_EMAIL_VERIFICATION=true
      - NEED_API_KEY=true  # Enable for production
      - SEND_ACCESS_TOKEN_TO_CLIENT=false
    volumes:
      - ./api-gateway:/app
      - /app/node_modules
    depends_on:
      kafka-1:
        condition: service_started
      kafka-2:
        condition: service_started  
      kafka-3:
        condition: service_started
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # All microservices - Internal only
  user-service:
    build:
      context: ./user-service
    container_name: user-service
    expose:
      - "8001"  # Internal only
    env_file:
      - ./user-service/.env
    volumes:
      - ./user-service:/app
      - /app/node_modules
      - ./libs:/libs
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  transport-service:
    build:
      context: ./transport-service
    container_name: transport-service
    expose:
      - "8002"    # HTTP
      - "50051"   # gRPC
    env_file:
      - ./transport-service/.env
    environment:
      - TRANSPORT_GRPC_PORT=50051
    volumes:
      - ./transport-service:/app
      - /app/node_modules
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  ticket-service:
    build:
      context: ./ticket-service
    container_name: ticket-service
    expose:
      - "8003"    # HTTP
      - "50052"   # gRPC
    env_file:
      - ./ticket-service/.env
    volumes:
      - ./ticket-service:/app
      - /app/node_modules
      - ./libs:/libs
    depends_on:
      kafka-1:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # customer-support-service:
  #   build:
  #     context: ./customer-support-service
  #   container_name: customer-support-service
  #   expose:
  #     - "8004"
  #   env_file:
  #     - ./customer-support-service/.env
  #   volumes:
  #     - ./customer-support-service:/app
  #   depends_on:
  #     redis:
  #       condition: service_healthy
  #   networks:
  #     - backend-network
  #   healthcheck:
  #     test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3004/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 40s
  #   restart: unless-stopped

  payment-service:
    build:
      context: ./payment-service
    container_name: payment-service
    expose:
      - "8005"
    env_file:
      - ./payment-service/.env
    volumes:
      - ./payment-service:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  report-service:
    build:
      context: ./report-service
    container_name: report-service
    expose:
      - "8006"
    env_file:
      - ./report-service/.env
    volumes:
      - ./report-service:/app
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8006/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  public-service:
    build:
      context: ./public-service
    container_name: public-service
    expose:
      - "8007"
    env_file:
      - ./public-service/.env
    environment:
      - SCHEDULER_ENABLED=true
      - TRANSPORT_SERVICE_GRPC_URL=transport-service:50051
      - TICKET_SERVICE_GRPC_URL=ticket-service:50052
    volumes:
      - ./public-service:/app
      - /app/node_modules
    depends_on:
      transport-service:
        condition: service_healthy
      ticket-service:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8007/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Health monitoring - Internal access only
  healthcheck:
    build:
      context: ./healthcheck
    container_name: healthcheck
    expose:
      - "3000"  # Internal only
    env_file:
      - ./healthcheck/.env
    volumes:
      - ./healthcheck:/app
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Database - Custom non-standard port, internal only
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB:-railway_system}
    expose:
      - "5432"  # Internal only
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Redis - Custom non-standard port, internal only  
  redis:
    image: redis:7-alpine
    container_name: redis
    expose:
      - "6379"  # Internal only
    volumes:
      - redis_data:/data
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes"]
    restart: unless-stopped

  # Management UIs - Separate compose file hoặc chỉ enable khi cần
  # Uncomment below for development/debugging only
  
  # redis-commander:
  #   image: rediscommander/redis-commander:latest
  #   container_name: redis-commander
  #   environment:
  #     - REDIS_HOSTS=local:redis:6379:0:${REDIS_PASSWORD}
  #   ports:
  #     - "127.0.0.1:8081:8081"  # Bind to localhost only
  #   depends_on:
  #     - redis
  #   networks:
  #     - backend-network
  #   profiles:
  #     - debug

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
  #     - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
  #   ports:
  #     - "127.0.0.1:5050:80"  # Bind to localhost only
  #   depends_on:
  #     - postgres
  #   networks:
  #     - backend-network
  #   volumes:
  #     - pgadmin_data:/var/lib/pgadmin
  #   profiles:
  #     - debug

  # Kafka Cluster - Internal only
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 5
      ZOOKEEPER_INIT_LIMIT: 10
    expose:
      - "2181"
    networks:
      - backend-network
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
    restart: unless-stopped

  kafka-1:
    image: confluentinc/cp-kafka:7.5.3
    container_name: kafka-1
    expose:
      - "9092"
      - "19092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:19092,EXTERNAL://kafka-1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:19092,EXTERNAL://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'  # Disable for production
    depends_on:
      - zookeeper
    networks:
      - backend-network
    volumes:
      - kafka1_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 15s
      timeout: 10s
      retries: 8
      start_period: 60s
    restart: unless-stopped

  kafka-2:
    image: confluentinc/cp-kafka:7.5.3
    container_name: kafka-2
    expose:
      - "9093"
      - "19093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:19093,EXTERNAL://kafka-2:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:19093,EXTERNAL://0.0.0.0:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    depends_on:
      - zookeeper
    networks:
      - backend-network
    volumes:
      - kafka2_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9093", "--list"]
      interval: 15s
      timeout: 10s
      retries: 8
      start_period: 60s
    restart: unless-stopped

  kafka-3:
    image: confluentinc/cp-kafka:7.5.3
    container_name: kafka-3
    expose:
      - "9094"
      - "19094"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:19094,EXTERNAL://kafka-3:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:19094,EXTERNAL://0.0.0.0:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    depends_on:
      - zookeeper
    networks:
      - backend-network
    volumes:
      - kafka3_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9094", "--list"]
      interval: 15s
      timeout: 10s
      retries: 8
      start_period: 60s
    restart: unless-stopped

  # Kafka UI - Only for debugging, disable in production
  # kafdrop:
  #   image: obsidiandynamics/kafdrop
  #   container_name: kafdrop
  #   ports:
  #     - "127.0.0.1:9000:9000"  # Localhost only
  #   environment:
  #     KAFKA_BROKERCONNECT: kafka-1:19092,kafka-2:19093,kafka-3:19094
  #     JVM_OPTS: '-Xms128M -Xmx256M'
  #   depends_on:
  #     - kafka-1
  #     - kafka-2
  #     - kafka-3
  #   networks:
  #     - backend-network
  #   profiles:
  #     - debug

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local
  zookeeper_data:
    driver: local
  kafka1_data:
    driver: local
  kafka2_data:
    driver: local
  kafka3_data:
    driver: local

networks:
  backend-network:
    driver: bridge
    internal: true  # Internal only network
  frontend-network:
    driver: bridge
    # External network for nginx only