apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/instance: {{ .Values.name }}
spec:
  {{- if .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml .Values.imagePullSecrets | nindent 4 }}
  {{- end }}
  replicas: {{ .Values.replicaCount | default .Values.global.replicaCount | default 2 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.name }}
      annotations:
        {{- if .Values.metricsPath }}
        prometheus.io/scrape: "true"
        prometheus.io/path: "{{ .Values.metricsPath }}"
        prometheus.io/port: "{{ .Values.metricsPort | default .Values.ports.http }}"
        {{- end }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ required "image.tag is required" .Values.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.ports.http }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.liveness.path | default .Values.probes.livenessPath }}
              port: http
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: {{ .Values.readiness.path | default .Values.probes.readinessPath }}
              port: http
            initialDelaySeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}


