const sequelize = require('../config/database');
const { DataTypes } = require('sequelize');

/**
 * Payment Model
 * @typedef {object} Payment
 * @property {number} paymentId - Primary key
 * @property {number} ticketId - Associated ticket ID (foreign key from ticket-service)
 * @property {number} passengerId - Associated passenger ID (foreign key from user-service)
 * @property {number} paymentAmount - Amount paid (VND)
 * @property {string} paymentMethod - Payment method (paypal, vnpay, card)
 * @property {string} paymentStatus - Status (PENDING, COMPLETED, FAILED)
 * @property {Date} paymentDate - Date/time of payment
 * @property {object} paymentGatewayResponse - Raw response from payment gateway (JSON)
 */
const Payment = sequelize.define('Payment', {
    /** Payment ID generated by ticket service */
    paymentId: {
        type: DataTypes.STRING,
        primaryKey: true,
        allowNull: false,
        comment: 'Payment ID generated by ticket service (format: TKT_TYPE_TICKETID_PAY_TIMESTAMP)'
    },
    ticketId: {
        type: DataTypes.STRING,
        allowNull: false
    },
    passengerId: {
        type: DataTypes.STRING,
        allowNull: false
    },
    paymentAmount: {
        type: DataTypes.DECIMAL(10, 2),
        allowNull: false
    },
    paymentMethod: {
        type: DataTypes.ENUM('paypal', 'vnpay', 'card'),
        allowNull: false
    },
    paymentStatus: {
        type: DataTypes.ENUM('PENDING', 'COMPLETED', 'FAILED'),
        allowNull: false
    },
    paymentDate: {
        type: DataTypes.DATE,
        allowNull: false
    },
    paymentGatewayResponse: {
        type: DataTypes.JSON,
        allowNull: true
    }
});

module.exports = Payment;