global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - "alert-rules.yml"

scrape_configs:
  - job_name: 'dashboard'
    metrics_path: /metrics
    file_sd_configs:
      - files:
        - /etc/prometheus/services.json
        refresh_interval: 10s
