name: transport-service
replicaCount: 2
image:
  repository: ghcr.io/CHANGE_ME_ORG/metro-transport-service
  tag: ""
ports:
  http: 8003
env:
  - name: NODE_ENV
    value: production
  - name: PORT
    value: "8003"
ingress:
  enabled: true
  host: transport.{{ .Values.global.domain }}
metricsPath: /metrics
metricsPort: 8003


