name: user-service
replicaCount: 2
image:
  repository: ghcr.io/CHANGE_ME_ORG/metro-user-service
  tag: ""
ports:
  http: 8002
env:
  - name: NODE_ENV
    value: production
  - name: PORT
    value: "8002"
ingress:
  enabled: true
  host: user.{{ .Values.global.domain }}
metricsPath: /metrics
metricsPort: 8002


