# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import control_pb2 as control__pb2

GRPC_GENERATED_VERSION = '1.65.5'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ControlServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateSchedule = channel.unary_unary(
                '/control.ControlService/GenerateSchedule',
                request_serializer=control__pb2.GenerateScheduleRequest.SerializeToString,
                response_deserializer=control__pb2.GenerateScheduleResponse.FromString,
                _registered_method=True)
        self.Reschedule = channel.unary_unary(
                '/control.ControlService/Reschedule',
                request_serializer=control__pb2.RescheduleRequest.SerializeToString,
                response_deserializer=control__pb2.RescheduleResponse.FromString,
                _registered_method=True)
        self.GetPlan = channel.unary_unary(
                '/control.ControlService/GetPlan',
                request_serializer=control__pb2.GetPlanRequest.SerializeToString,
                response_deserializer=control__pb2.GetPlanResponse.FromString,
                _registered_method=True)
        self.GenerateDailySchedules = channel.unary_unary(
                '/control.ControlService/GenerateDailySchedules',
                request_serializer=control__pb2.GenerateDailyRequest.SerializeToString,
                response_deserializer=control__pb2.GenerateScheduleResponse.FromString,
                _registered_method=True)


class ControlServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reschedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateDailySchedules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateSchedule,
                    request_deserializer=control__pb2.GenerateScheduleRequest.FromString,
                    response_serializer=control__pb2.GenerateScheduleResponse.SerializeToString,
            ),
            'Reschedule': grpc.unary_unary_rpc_method_handler(
                    servicer.Reschedule,
                    request_deserializer=control__pb2.RescheduleRequest.FromString,
                    response_serializer=control__pb2.RescheduleResponse.SerializeToString,
            ),
            'GetPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlan,
                    request_deserializer=control__pb2.GetPlanRequest.FromString,
                    response_serializer=control__pb2.GetPlanResponse.SerializeToString,
            ),
            'GenerateDailySchedules': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateDailySchedules,
                    request_deserializer=control__pb2.GenerateDailyRequest.FromString,
                    response_serializer=control__pb2.GenerateScheduleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'control.ControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('control.ControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control.ControlService/GenerateSchedule',
            control__pb2.GenerateScheduleRequest.SerializeToString,
            control__pb2.GenerateScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reschedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control.ControlService/Reschedule',
            control__pb2.RescheduleRequest.SerializeToString,
            control__pb2.RescheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control.ControlService/GetPlan',
            control__pb2.GetPlanRequest.SerializeToString,
            control__pb2.GetPlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateDailySchedules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/control.ControlService/GenerateDailySchedules',
            control__pb2.GenerateDailyRequest.SerializeToString,
            control__pb2.GenerateScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
