name: CD
run-name: ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.display_title) || (github.event_name == 'workflow_dispatch' && format('Deploy {0}', inputs.tag || github.ref_name || github.sha)) || format('Deploy {0}', github.ref_name || github.sha) }}

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [ main ]
  workflow_dispatch:
    inputs:
      tag:
        description: Image tag to deploy (semver vX.Y.Z or short SHA). Leave empty to use computed tag
        required: false

permissions:
  contents: read
  packages: read

env:
  DEFAULT_VPS_PATH: /opt/metro
  REGISTRY: ghcr.io/${{ github.repository_owner }}
  GHCR_HOST: ghcr.io

jobs:
  deploy-vps:
    name: Local deploy on self-hosted runner
    runs-on: [self-hosted]
    timeout-minutes: 30
    if: >
      ${{
        github.event_name == 'workflow_dispatch' ||
        (
          github.event_name == 'workflow_run' &&
          github.event.workflow_run.conclusion == 'success' &&
          github.event.workflow_run.event == 'push'
        )
      }}
    concurrency:
      group: deploy-selfhosted-${{ github.ref_name }}
      cancel-in-progress: false

    steps:
      - name: Normalize REGISTRY (lowercase owner)
        shell: bash
        run: echo "REGISTRY=ghcr.io/${GITHUB_REPOSITORY_OWNER,,}" >> "$GITHUB_ENV"

      - name: Clean workspace before checkout
        shell: bash
        run: |
          chmod -R u+w "$GITHUB_WORKSPACE" 2>/dev/null || true
          rm -rf "$GITHUB_WORKSPACE/nginx/certs/" "$GITHUB_WORKSPACE/.git/" 2>/dev/null || true
          sudo chown -R "$(whoami):$(whoami)" "$GITHUB_WORKSPACE" 2>/dev/null || true

      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Resolve deploy tag
        id: tag
        shell: bash
        run: |
          set -euo pipefail
          if [[ -n "${{ inputs.tag || '' }}" ]]; then
            echo "value=${{ inputs.tag }}" >> "$GITHUB_OUTPUT"
          elif [[ "${{ github.event_name }}" == "workflow_run" ]]; then
            SHA="${{ github.event.workflow_run.head_sha }}"
            echo "value=${SHA:0:7}" >> "$GITHUB_OUTPUT"
          else
            echo "value=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
          fi
          echo "Resolved tag: $(sed -n 's/^value=//p' "$GITHUB_OUTPUT")"

      - name: Docker login GHCR
        env:
          GHCR_HOST: ${{ env.GHCR_HOST }}
          REGISTRY_USER: ${{ secrets.GHCR_USERNAME || github.actor }}
          REGISTRY_TOKEN: ${{ secrets.GHCR_TOKEN || secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          set -e
          echo "$REGISTRY_TOKEN" | docker login "$GHCR_HOST" -u "$REGISTRY_USER" --password-stdin

      - name: Verify images exist for tag
        env:
          REGISTRY: ${{ env.REGISTRY }}
          IMAGE_TAG: ${{ steps.tag.outputs.value }}
        shell: bash
        run: |
          set -euo pipefail
          REGISTRY_LC="$(echo "$REGISTRY" | tr '[:upper:]' '[:lower:]')"
          services=(
            api-gateway auth-service payment-service public-service ticket-service
            transport-service user-service report-service management-service
            control-service notification-service webhook scheduler-service
          )
          missing=()
          for s in "${services[@]}"; do
            ref="$REGISTRY_LC/metro-$s:$IMAGE_TAG"
            echo "Checking $ref"
            if ! docker manifest inspect "$ref" >/dev/null 2>&1; then
              missing+=("$ref")
            fi
          done
          if (( ${#missing[@]} > 0 )); then
            echo "Missing images for tag '$IMAGE_TAG':" >&2
            printf ' - %s\n' "${missing[@]}" >&2
            exit 1
          fi
          echo "All images for '$IMAGE_TAG' are present."

      - name: Compose pull & up
        env:
          TAG: ${{ steps.tag.outputs.value }}
          IMAGE_TAG: ${{ steps.tag.outputs.value }}
          VPS_PATH: ${{ secrets.VPS_PATH || env.DEFAULT_VPS_PATH }}
          COMPOSE_PROFILES: nginx,admin-tools
        shell: bash
        run: |
          set -euo pipefail
          DEPLOY_DIR="$GITHUB_WORKSPACE"
          if [ ! -f "$DEPLOY_DIR/docker-compose.prod.yml" ] \
             && [ ! -f "$DEPLOY_DIR/compose.prod.yml" ] \
             && [ ! -f "$DEPLOY_DIR/docker-compose.yml" ] \
             && [ ! -f "$DEPLOY_DIR/compose.yml" ]; then
            DEPLOY_DIR="${VPS_PATH:-/opt/metro}"
          fi
          echo "Using deploy directory: $DEPLOY_DIR"
          cd "$DEPLOY_DIR"

          docker compose version >/dev/null

          if   [ -f docker-compose.prod.yml ]; then COMPOSE_FILES="-f docker-compose.prod.yml"
          elif [ -f compose.prod.yml ];        then COMPOSE_FILES="-f compose.prod.yml"
          elif [ -f docker-compose.yml ];      then COMPOSE_FILES="-f docker-compose.yml"
          elif [ -f compose.yml ];             then COMPOSE_FILES="-f compose.yml"
          else echo "No compose file found in $DEPLOY_DIR" >&2; exit 1; fi

          echo "Using tag: $TAG"
          echo "Using profiles: $COMPOSE_PROFILES"

          docker compose $COMPOSE_FILES pull || true
          docker compose $COMPOSE_FILES --profile nginx --profile admin-tools up -d --remove-orphans

          docker image prune -f || true
          docker compose $COMPOSE_FILES ps
