name: CI

on:
  pull_request:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  packages: write
  security-events: write
  actions: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

# REGISTRY thống nhất toàn pipeline (lowercase owner)
env:
  REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build-test-scan-push:
    runs-on: [self-hosted]

    outputs:
      short_tag: ${{ steps.vars.outputs.short_sha }}
      is_release: ${{ steps.vars.outputs.is_release }}
      release_tag: ${{ steps.vars.outputs.release_tag }}

    env:
      ENABLE_SARIF_UPLOAD: 'false'

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: api-gateway
            path: api-gateway
            dockerfile: Dockerfile
            runtime: node
          - name: auth-service
            path: auth-service
            dockerfile: Dockerfile
            runtime: node
          - name: payment-service
            path: payment-service
            dockerfile: Dockerfile
            runtime: node
          - name: public-service
            path: public-service
            dockerfile: Dockerfile
            runtime: node
          - name: ticket-service
            path: ticket-service
            dockerfile: Dockerfile
            runtime: node
          - name: transport-service
            path: transport-service
            dockerfile: Dockerfile
            runtime: node
          - name: control-service
            path: control-service
            dockerfile: Dockerfile
            runtime: python
          - name: user-service
            path: user-service
            dockerfile: Dockerfile
            runtime: node
          - name: report-service
            path: report-service
            dockerfile: Dockerfile
            runtime: python
          - name: notification-service
            path: notification-service
            dockerfile: Dockerfile
            runtime: node
          - name: management-service
            path: management-service
            dockerfile: Dockerfile
            runtime: python
          - name: webhook
            path: webhook
            dockerfile: Dockerfile
            runtime: node

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------- Setup runtimes & caches ----------
      - name: Use Node.js
        if: matrix.runtime == 'node'
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Detect npm lockfile
        id: detect_lockfile
        if: ${{ matrix.runtime == 'node' }}
        run: |
          if [ -f "${{ matrix.path }}/package-lock.json" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Ensure npm cache directory
        id: ensure_npm_cache_dir
        if: ${{ matrix.runtime == 'node' }}
        shell: bash
        run: |
          NPM_CACHE_DIR=$(npm config get cache)
          mkdir -p "$NPM_CACHE_DIR"
          echo "npm_cache_dir=$NPM_CACHE_DIR" >> $GITHUB_OUTPUT

      - name: Cache npm (when lockfile exists)
        if: ${{ matrix.runtime == 'node' && steps.detect_lockfile.outputs.exists == 'true' }}
        uses: actions/cache@v4
        with:
          path: ${{ steps.ensure_npm_cache_dir.outputs.npm_cache_dir }}
          key: ${{ runner.os }}-node-${{ hashFiles(format('{0}/package-lock.json', matrix.path)) }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install deps (Node)
        if: matrix.runtime == 'node'
        working-directory: ${{ matrix.path }}
        run: |
          npm ci --no-audit --no-fund || (
            echo "npm ci failed, syncing lockfile..." && \
            npm install --package-lock-only --no-audit --no-fund && \
            npm ci --no-audit --no-fund
          )

      - name: Set ENFORCE_COVERAGE
        if: matrix.runtime == 'node'
        run: |
          if [[ "${{ github.event_name }}" == 'push' && "${{ github.ref }}" == refs/heads/main ]]; then
            echo "ENFORCE_COVERAGE=true" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            echo "ENFORCE_COVERAGE=true" >> $GITHUB_ENV
          else
            echo "ENFORCE_COVERAGE=false" >> $GITHUB_ENV
          fi

      - name: Test (Node)
        if: matrix.runtime == 'node'
        working-directory: ${{ matrix.path }}
        run: |
          if npm run | grep -q "test"; then
            npm test --if-present
          fi
          if npm run | grep -q "test:coverage" && [[ "$ENFORCE_COVERAGE" == "true" ]]; then
            npm run test:coverage
          fi

      - name: Use Python
        if: matrix.runtime == 'python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        if: matrix.runtime == 'python'
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles(format('{0}/requirements.txt', matrix.path)) }}-${{ hashFiles(format('{0}/requirements-dev.txt', matrix.path)) }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps (Python)
        if: matrix.runtime == 'python'
        working-directory: ${{ matrix.path }}
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Test (Python)
        if: matrix.runtime == 'python'
        working-directory: ${{ matrix.path }}
        run: |
          if [ -d tests ]; then pytest -q || true; fi

      # ---------- Build & Push ----------
      - name: Compute tags
        id: vars
        run: |
          echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            echo "is_release=true" >> $GITHUB_OUTPUT
            echo "release_tag=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          else
            echo "is_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image (SHA tag)
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.path }}
          file: ${{ matrix.path }}/${{ matrix.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          load: ${{ github.event_name == 'pull_request' }}
          cache-from: type=gha,scope=metro-${{ matrix.name }}
          cache-to: type=gha,mode=max,scope=metro-${{ matrix.name }}
          tags: |
            ${{ env.REGISTRY }}/metro-${{ matrix.name }}:${{ steps.vars.outputs.short_sha }}
          build-args: |
            APP_VERSION=${{ steps.vars.outputs.short_sha }}

      - name: Also push release semver tag when building a tag
        if: steps.vars.outputs.is_release == 'true'
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.path }}
          file: ${{ matrix.path }}/${{ matrix.dockerfile }}
          push: true
          cache-from: type=gha,scope=metro-${{ matrix.name }}
          cache-to: type=gha,mode=max,scope=metro-${{ matrix.name }}
          tags: |
            ${{ env.REGISTRY }}/metro-${{ matrix.name }}:${{ steps.vars.outputs.release_tag }}
          build-args: |
            APP_VERSION=${{ steps.vars.outputs.release_tag }}

      # ---------- (Optional) Trivy chỉ khi release tag ----------
      - name: Prepare Trivy cache dir
        if: steps.vars.outputs.is_release == 'true'
        run: |
          mkdir -p "$HOME/.cache/trivy"
          echo "TRIVY_CACHE_DIR=$HOME/.cache/trivy" >> $GITHUB_ENV

      - name: Restore Trivy DB cache
        if: steps.vars.outputs.is_release == 'true'
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.TRIVY_CACHE_DIR }}
          key: ${{ runner.os }}-trivy-db-${{ matrix.name }}
          restore-keys: |
            ${{ runner.os }}-trivy-db-

      - name: Pull image for scan (release only)
        if: steps.vars.outputs.is_release == 'true'
        run: docker pull "$REGISTRY/metro-${{ matrix.name }}:${{ steps.vars.outputs.short_sha }}"

      - name: Trivy scan (release only)
        if: steps.vars.outputs.is_release == 'true'
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ env.REGISTRY }}/metro-${{ matrix.name }}:${{ steps.vars.outputs.short_sha }}
          format: sarif
          output: trivy-${{ matrix.name }}.sarif
          vuln-type: 'os,library'
          exit-code: '0'
          github-pat: ${{ secrets.GITHUB_TOKEN }}
          cache-dir: ${{ env.TRIVY_CACHE_DIR }}
          timeout: 5m
          hide-progress: true

      - name: Save Trivy DB cache
        if: steps.vars.outputs.is_release == 'true'
        uses: actions/cache/save@v4
        with:
          path: ${{ env.TRIVY_CACHE_DIR }}
          key: ${{ runner.os }}-trivy-db-${{ matrix.name }}

      - name: Upload SARIF
        if: steps.vars.outputs.is_release == 'true' && env.ENABLE_SARIF_UPLOAD == 'true'
        uses: github/codeql-action/upload-sarif@v3
        continue-on-error: true
        with:
          sarif_file: trivy-${{ matrix.name }}.sarif

      - name: Cleanup Docker & caches
        if: always()
        run: |
          docker system prune -af --volumes || true
          rm -rf ~/.cache/npm/_cacache || true
          rm -rf ~/.cache/pip || true

  verify-images:
    # Chỉ verify khi push (PR không push image)
    if: github.event_name == 'push'
    runs-on: [self-hosted, linux, x64, ci]
    needs: build-test-scan-push
    strategy:
      fail-fast: false
      matrix:
        image:
          - metro-api-gateway
          - metro-auth-service
          - metro-payment-service
          - metro-public-service
          - metro-ticket-service
          - metro-transport-service
          - metro-control-service
          - metro-user-service
          - metro-report-service
          - metro-notification-service
          - metro-management-service
          - metro-webhook
    steps:
      - name: Login GHCR (read)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify image exists with short tag
        shell: bash
        run: |
          TAG="${{ needs.build-test-scan-push.outputs.short_tag }}"
          REF="${{ env.REGISTRY }}/${{ matrix.image }}:${TAG}"
          echo "Checking $REF"
          if ! docker manifest inspect "$REF" > /dev/null 2>&1; then
            echo "Missing image: $REF"
            exit 1
          fi
          echo "OK: $REF"

  deploy:
    # Tùy chọn: chỉ chạy khi push vào main (tránh deploy khi tag nếu bạn muốn tách riêng)
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: [self-hosted, linux, x64, ci]
    needs: verify-images
    env:
      VPS_PATH: ${{ secrets.VPS_PATH || '/opt/metro' }}
    steps:
      - name: Show context
        run: |
          echo "Using VPS_PATH=$VPS_PATH"
          echo "REGISTRY=$REGISTRY"
          echo "TAG=${{ needs.build-test-scan-push.outputs.short_tag }}"

      - name: Pull newest images
        run: |
          TAG="${{ needs.build-test-scan-push.outputs.short_tag }}"
          SERVICES=(
            api-gateway auth-service payment-service public-service ticket-service
            transport-service control-service user-service report-service
            notification-service management-service webhook
          )
          for s in "${SERVICES[@]}"; do
            img="${REGISTRY}/metro-${s}:${TAG}"
            echo "Pulling $img"
            docker pull "$img"
          done

      - name: Compose pull & up
        working-directory: ${{ env.VPS_PATH }}
        env:
          TAG: ${{ needs.build-test-scan-push.outputs.short_tag }}
        run: |
          set -euo pipefail
          export TAG
          # Giả định docker-compose.yml dùng biến ${TAG} cho từng service
          docker compose pull
          docker compose up -d
          docker compose ps
